[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build",
    "cmake>=3.17",
    "ninja",
    "nanobind==1.9.2",
    "typing_extensions",
]

build-backend = "setuptools.build_meta"
